/** @type {import("tailwindcss").Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        canvas: "rgb(var(--surface-canvas-rgb) / <alpha-value>)",
        surface: "rgb(var(--surface-primary-rgb) / <alpha-value>)",
        "surface-soft": "rgb(var(--surface-secondary-rgb) / <alpha-value>)",
        elevated: "rgb(var(--surface-elevated-rgb) / <alpha-value>)",
        glass: "var(--surface-glass)",
        ink: "rgb(var(--text-primary-rgb) / <alpha-value>)",
        "ink-soft": "rgb(var(--text-secondary-rgb) / <alpha-value>)",
        muted: "rgb(var(--text-tertiary-rgb) / <alpha-value>)",
        line: "rgb(var(--border-default-rgb) / <alpha-value>)",
        "line-soft": "var(--border-subtle)",
        accent: "rgb(var(--accent-primary-rgb) / <alpha-value>)",
        "accent-hover": "rgb(var(--accent-hover-rgb) / <alpha-value>)",
        idea: "rgb(var(--step-idea-rgb) / <alpha-value>)",
        problem: "rgb(var(--step-problem-rgb) / <alpha-value>)",
        goal: "rgb(var(--step-goal-rgb) / <alpha-value>)",
        mvp: "rgb(var(--step-mvp-rgb) / <alpha-value>)",
        roles: "rgb(var(--step-roles-rgb) / <alpha-value>)",
        issues: "rgb(var(--step-issues-rgb) / <alpha-value>)",
        success: "rgb(var(--status-success-rgb) / <alpha-value>)",
        warning: "rgb(var(--status-warning-rgb) / <alpha-value>)",
        danger: "rgb(var(--status-error-rgb) / <alpha-value>)",
        info: "rgb(var(--status-info-rgb) / <alpha-value>)",
        "preview-canvas": "var(--preview-canvas)",
        "preview-sidebar": "var(--preview-sidebar)",
        "preview-main": "var(--preview-main)",
        "preview-brand": "var(--preview-brand)",
      },
      fontFamily: {
        sans: [
          '"Nimbus Sans TW01"',
          '"Helvetica Neue"',
          "Helvetica",
          "Arial",
          '"Apple SD Gothic Neo"',
          "Pretendard",
          '"Noto Sans KR"',
          "sans-serif",
        ],
      },
      borderRadius: {
        "app-sm": "var(--radius-sm)",
        "app-md": "var(--radius-md)",
        "app-lg": "var(--radius-lg)",
        pill: "9999px",
      },
      boxShadow: {
        soft: "var(--shadow-soft)",
        dialog: "var(--shadow-dialog)",
      },
    },
  },
  plugins: [],
};
